spring.application.name=SpringBootMvc_With_Pagination

# View resolver configuration
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

# Embedded server port number
#server.port=4050

# Context path
#server.servlet.context-path=/Employee-CurdOperations

# Datasource Configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=c##oracle11am
spring.datasource.password=nareshit11

# Hibernate JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect